language: python
python:
  - 3.6
sudo: required

services:
  - docker

install:
  - pip install -r ansible-requirements.txt
  - pip install -r test-requirements.txt

script:
  - ansible-lint --version
  - ansible-lint site.yml
  - ansible-lint roles/*
  - cd roles/secure-docker-ca-client
  - molecule test --all --destroy always
  - cd ../secure-docker-server
  - molecule test --all --destroy always
