---
- name: Provisioning GCP VMs
  hosts: localhost
  gather_facts: no
  connection: local


#   roles:
#   - role: gcpvm

  roles:
  - role: gcpvm
    instance_name: vm-test-1
  - role: gcpvm
    instance_name: vm-test-2

#   tasks:
#     - include_role:
#         name: gcpvm
#       vars:
#         instance_name: "{{ item }}"
#       with_items:
#         - vm-test-1
#         - vm-test-2  

#   tasks:       
#     - name: Pass variables to role
#       include_role:
#         name: gcpvm
#       vars:
#         instance_name: vm-prova
