---
- import_playbook: playbooks/create_infra.yml
- import_playbook: playbooks/mount_docker_disk.yml
- import_playbook: playbooks/install_docker_swarm.yml
- import_playbook: playbooks/secure_docker_swarm.yml
