---
scenario:
  name: docker
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
  inventory:
    group_vars:
      all:
        pki_path: pki
        docker_client_certs_path: /root/.docker
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  directory: ../resources/tests
  options:
    v: true
    s: true
  lint:
    name: flake8
