---
- name: Secure Docker Swarm - local
  hosts: localhost
  gather_facts: no
  connection: local

  roles:
    - role: secure-docker-local
      tags:
        - create
        - configure

- name: Secure Docker Swarm - remote
  hosts: all
  become: yes

  roles:
    - role: secure-docker-remote
      tags:
        - create
        - configure