---
- name: create a disk
  gcp_compute_disk:
    name: "{{ instance_name }}"
    size_gb: "{{ size_gb }}"
    source_image: 'projects/centos-cloud/global/images/centos-7-v20190116'
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: disk

- name: create an instance
  gcp_compute_instance:
    name: "{{ instance_name }}"
    machine_type: "{{ machine_type }}"
    disks:
    - auto_delete: true
      boot: true
      source: "{{ disk }}"
    network_interfaces:
    - network: 
        selfLink: 'projects/ansible-cc/global/networks/default'
      subnetwork: 
        selfLink: 'projects/ansible-cc/regions/us-central1/subnetworks/default'
      access_configs:
        - name: 'External NAT'
          type: 'ONE_TO_ONE_NAT'
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
    tags:
      items:
        - docker
        - http
  register: instance

# - name: Wait for SSH to come up
#   wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
#   with_items: "{{ instance.instance_data }}"