---
- name: create root disk
  gcp_compute_disk:
    name: "{{ instance_name }}-root"
    source_image: 'projects/gce-uefi-images/global/images/centos-7-v20191014'
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: disk_root

- name: create docker disk
  gcp_compute_disk:
    name: "{{ instance_name }}-docker"
    size_gb: "{{ size_gb }}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: disk_docker

- name: create an instance
  gcp_compute_instance:
    name: "{{ instance_name }}"
    machine_type: "{{ machine_type }}"
    disks:
    - auto_delete: true
      boot: true
      source: "{{ disk_root }}"
    - auto_delete: true
      source: "{{ disk_docker }}"
    network_interfaces:
    - network: 
        selfLink: 'projects/ansible-cc/global/networks/default'
      subnetwork: 
        selfLink: 'projects/ansible-cc/regions/us-central1/subnetworks/default'
      access_configs:
        - name: 'External NAT'
          type: 'ONE_TO_ONE_NAT'
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
    tags:
      items:
        - docker
        - http
  register: instance

- name: wait for SSH to come up
  delegate_to: "{{ instance.networkInterfaces[0].accessConfigs[0].natIP }}"
  wait_for_connection:
    timeout: 120

# - name: Wait for SSH to come up
#   wait_for: host={{ instance.networkInterfaces[0].accessConfigs[0].natIP }} port=22 delay=10 timeout=60